### PR TITLE
Initial work around deployment to Google Container Engine

### PR DESCRIPTION
**Pull request by casibbald**

### CODE REVIEW

**Comment by flopezlasanta** [comment]
Hi casibbald, I'm interested in having this feature. Are you still on it? Thanks!

**Comment by casibbald** [comment]
Yes, I have been working on making it prettier. But also looking at an amalgamation of the other recently suggested project.
Will have it working well soon.
I have to make some changes to move the docker components into sub modules.
Will finish it up this weekend and you guys can provide some valuable critique.

**Comment by casibbald** [comment]
Hi All,

I have spent a little more time on this and I would like to know if anyone has any objection to the following:

In Kubernetes we would package the deployment as follows:

1. Postgres Pod (Could be further developed to active-active cluster)
2. Django (Without nginx)
3. Nginx provided by Kubernetes Ingres
3. Webpack JS/CSS files pushed to cloudstorage buckets and then served via cloudflare.

Every build would produce a new cloud flare bucket, with static files.

Up to the bucket owner to clean up older buckets, or we can implement a cleanup process.

Regards

Charles

**Comment by lfrodrigues** [comment]
Thanks for this @casibbald . Would it be possible to put all google could related files in the gce folder? I would prefer not to pollute the root with more files.

**Comment by casibbald** [comment]
Yes happy to do that.
Actually intend to switch it to helm charts. So will update and make changes

**Pull request closed without merging**
